name: Node.js test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['20']
        java: ['17']
        vite-version: ['6', '7', '8']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK ${{ matrix.java }}
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:1.${{ matrix.java }}
        apps: sbt

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies with Vite ${{ matrix.vite-version }}
      run: npm install -D @types/node@${{ matrix.node-version }} && npm install vite@${{ matrix.vite-version }}
    - name: Run sbt once in the test project to make sure sbt is downloaded
      run: sbt projects
      working-directory: ./test/sbt-project
    - name: Run sbt once in the sbt 2 test project
      run: sbt "projects ; shutdown"
      working-directory: ./test/sbt-2-project
    - name: Perform unit test
      run: npm test
    - name: Build
      run: npm run build
